### ISSUE TITLE
creating and storing hashes for each valid BCO JSON

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_editor#10]
Using the process outlined by scrips/packages in the [`checksum_tool`](https://github.com/biocompute-objects/checksum_tool) repo:

1) The website should be able to generate a stable BCO file upon successful validation, less the `checksum` feild. 

2) That file will be processed as outlined in the [checksum](https://github.com/biocompute-objects/checksum_tool/blob/master/sha256.py) script

3) the resulting BCO will be saved with the new string included in the `checksum` feild. 

4) This should happen ANY time a BCO is updated/modified.

**Comment by HadleyKing** [comment]
@HadleyKing ,
A question on submitting BCOs. Shouldn't the checksum field be left empty by a submitter? As I understand our submission workflow, the editor should create a hash and populate the checksum field. 
However when I submit a BCO without the checksum field I get an error message stating that the checksum is invalid?
Can you please clarify? We are trying to test the hashing step in the validator.
Thanks,
 @openbox-bio

**Comment by HadleyKing** [comment]
@openbox-bio 
My understanding is that is happening because the `validate.py` is trying to validate the BCO before it has a `checksum` value, and so it is throwing the error. A few workarounds/hack come to mind... either have the `validate.py` do the validation AFTER the `checksum` is calculated, or have a way to bypass the throwing of that error...

**Comment by openbox-bio** [comment]
We have implemented this. Suggest to close issue.

**Comment by HadleyKing** [comment]
> We have implemented this. Suggest to close issue.

can you provide the commit hash and we can close?

**Comment by openbox-bio** [comment]
Hadley,
Writing to confirm that we can close this issue.
-Anjan
=======================================

“Don't be satisfied with stories, how things have gone with others.

Unfold your own myth.”
― Rumi,

========================================

**Comment by openbox-bio** [comment]
This is done.
