### ISSUE TITLE
Update Schema

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_editor#101]
Schema for BCO Editor needs to be based on the [1.4.0](https://raw.githubusercontent.com/biocompute-objects/BCO_Specification/1.4.0/schemas/biocomputeobject.json) standard.

**Comment by jpat1546** [comment]
works
please close with commit @ITsolution-git

**Comment by HadleyKing** [comment]
see #140

**Comment by jpat1546** [comment]
duplicates #140
