### ISSUE TITLE
Interface change

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_editor#11]
Super minor, but all the domains seem to **bolded**? The older interface looked cleaner. See below pics: 

![Screenshot 2019-08-06 14 52 16](https://user-images.githubusercontent.com/20343214/62567729-c9dfd380-b859-11e9-81a0-13c57ef4a9a7.png)

**Comment by jpat1546** [comment]
visual separation of domains- while block in btw?

**Comment by openbox-bio** [comment]
See issue 25.

**Comment by openbox-bio** [comment]
Un-bolding field names and visual separation of domains has been completed. Please check.
