### ISSUE TITLE
Spelling Issues on Dashboard - 'Bco Object'

### ISSUE THREAD

**Issue by Snehby** [biocompute-objects/bco_editor#110]
![2020_03_03_13_14_05_BioComputeObject](https://user-images.githubusercontent.com/12602831/75807043-b98dc980-5d52-11ea-9aa8-617d79a8560e.png)

Should be 'BioCompute Object List' and 'Create New BCO' 
@ITsolution-git

**Comment by jpat1546** [comment]
<img width="402" alt="Screen Shot 2020-05-04 at 11 47 10 AM" src="https://user-images.githubusercontent.com/23385872/81001840-51bd3300-8e16-11ea-8bf5-250f431b0941.png">
