### ISSUE TITLE
Parametric, Extension, and Error Domains prevent advancing to save BCO, but they should be optional

### ISSUE THREAD

**Issue by kee007ney** [biocompute-objects/bco_editor#113]
In the Editor, Parametric, Extension, and Error Domains are all required and will not let the user advance. None of these are required domains in the current BCO spec.

The error raised with Extension Domain is that it needs to be formatted as an array, but it gives this error even if nothing is there, so it's effectively making this field required. This error should only come up if there is content in the Extension Domain. If it's empty, it should let the BCO pass.

**Comment by ITsolution-git** [comment]
https://github.com/biocompute-objects/bco_editor/commit/b38a1b1c503cee2463dfd1bfc60d320384a658fd

**Comment by ITsolution-git** [comment]
https://github.com/biocompute-objects/bco_editor/commit/000a3c8664a0425918cfb6078727729d0d8773b8

**Comment by jpat1546** [comment]
Still requiring these domains : 

![image](https://user-images.githubusercontent.com/23385872/81003653-2f78e480-8e19-11ea-87fb-689799e00c1b.png)

![image](https://user-images.githubusercontent.com/23385872/81003677-39024c80-8e19-11ea-9f14-a70406ed6603.png)

**Comment by jpat1546** [comment]
Domains no longer required- users can save their BCO with no input in the PD, Error Domain, and Extension Domain. 

Issue will be completely resolved once asterisk* is removed from the PD header. Thanks!

**Comment by jpat1546** [comment]
Parametric domain still being required in 3.0.2

**Comment by jpat1546** [comment]
closing and splitting into separate issues. #146
