### ISSUE TITLE
E-TAG

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_editor#114]
The etag is a required field, but asks the user to input this. We're supposed to provide this for them by filling in a SHA256 checksum when they click submit.

The last version worked by having a -1 in that field until the user clicks submit. That's fine, or if we can just gray it out so the user can't touch it, that would be even better.

**Comment by ITsolution-git** [comment]
https://github.com/biocompute-objects/bco_editor/commit/b38a1b1c503cee2463dfd1bfc60d320384a658fd

**Comment by HadleyKing** [comment]
This is broken. Now it is greyed out but it is a required property. the current default does not work.

**Comment by HadleyKing** [comment]
628043c385b6ff5e017da5cd55faea53c84b21eb
