### ISSUE TITLE
environment_variables

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_editor#115]
the "environment_variables" (bottom of Execution Domain) field does not expand, so we can't enter information there.

**Comment by ITsolution-git** [comment]
https://github.com/biocompute-objects/bco_editor/commit/5a6dc8a2c772ee1f53060713d9a233dfca2a8d5a

**Comment by HadleyKing** [comment]
Currently this gives the error message "environment_variables: should be array"
That is incorrect. 
See https://github.com/biocompute-objects/BCO_Specification/blob/1ee53d0747dda17080c021f85ddbd709b53633f3/ieee-2791-schema/execution_domain.json#L100-L109

**Comment by carmstrong1gw** [comment]
Void, will be fixed with schema UI.
