### ISSUE TITLE
Check for Duplicate BCO

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_editor#12]
@jpat1546 wrote: took raw json of HCV1a from Git, created a new object. Major issue

@openbox-bio: Is it because you do not want the editor to create a BCO from a raw JSON file? Or is it because the a BCO for HCV1a already exists and therefore the editor should not create a duplicate BCO?

@jpat1546: the editor should identify that that particular BCO for HCV1a already exists and therefore should not create a duplicate BCO

**Comment by openbox-bio** [comment]
Hadley This has been implemented in the latest commit: Please see:
https://github.com/openbox-bio/bco_editor/commit/f4720ceccf05a90ee985ca6192da29ee676f8e10

**Comment by jpat1546** [comment]
@openbox-bio Great- the editor now prohibits the user from saving the json of an existing BCO! Any chance we can change the message from "invalid json" to "Duplicate BCO" ?
<img width="472" alt="image" src="https://user-images.githubusercontent.com/23385872/63136584-aa0a8700-bfa0-11e9-90f5-1c3cbf51d78b.png">

Thanks!

**Comment by openbox-bio** [comment]
Noted.
-Anjan
=======================================

“Don't be satisfied with stories, how things have gone with others.

Unfold your own myth.”
― Rumi,

========================================

**Comment by jpat1546** [comment]
<img width="370" alt="image" src="https://user-images.githubusercontent.com/23385872/63236803-2ef9d880-c20d-11e9-98c8-d411f6598109.png">
