### ISSUE TITLE
Tutorial Text

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_editor#120]
Currently the tutorial is hard coded. It needs to be pulled from `~/docs/User_Tutorial.md` upon Build.

https://github.com/biocompute-objects/bco_editor/blob/32bb42a194d9c2bf88f580431e04f2aa200ad988/frontend/src/views/Icons/Icons.js#L26

**Comment by carmstrong1gw** [comment]
Void, works as of 3.0.1
