### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_editor#13]
@jpat1546: Help text says: "All BioCompute object types must adhear to this type."  This should be adhere

**Comment by jpat1546** [comment]
Additional typo: "Extenion domain" -→ should be "Extension domain"

**Comment by openbox-bio** [comment]
I believe adhear has been corrected to adhere. 
Where does "Extenion" show up?

**Comment by jpat1546** [comment]
Just checked- it has been corrected on test. Below pic is from prd:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/23385872/62966349-dc678900-bdd4-11e9-8f2a-9c16bca13656.png">
