### ISSUE TITLE
Timed error messages

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#14]
![image](https://user-images.githubusercontent.com/23385872/62571079-758b2280-b85e-11e9-9293-caab0ae47936.png)

Error messages disappear- should stay until User X-es out

**Comment by openbox-bio** [comment]
This has been addressed in the current dev version.

**Comment by HadleyKing** [comment]
> This has been addressed in the current dev version.

@openbox-bio can you either quote the commit in text when closing an issue or use the `fixed #<issue number>` as outlined in the [git docs](https://help.github.com/en/articles/closing-issues-using-keywords)
