### ISSUE TITLE
Extension Domain requirement and restrictions

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#147]
![image](https://user-images.githubusercontent.com/23385872/87184617-2f73e580-c29d-11ea-8a43-acfe9e7cbb65.png)

Extension domain not required, and when no value, this error is generated

**Comment by jpat1546** [comment]
![Uploading image.png…]()

**Comment by jpat1546** [comment]
<img width="201" alt="Screen Shot 2020-07-21 at 11 36 35 AM" src="https://user-images.githubusercontent.com/23385872/88093371-c7e45280-cb46-11ea-9b60-20dfda978411.png">

**Comment by carmstrong1gw** [comment]
Void, will be fixed with schema UI.
