### ISSUE TITLE
Extension domain URI

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#149]
should be 2 objects---> 1) schema URI and 2) user-defined object with nestedkey/value ext pairs
![image](https://user-images.githubusercontent.com/23385872/87198549-a31eee00-c2af-11ea-84ac-da1d90ad90fc.png)

**Comment by jpat1546** [comment]
(this is why Portal is not parsing the dataset_categories from the CPed JSON into the form)

**Comment by jpat1546** [comment]
Long term goal will be this option: 
![image](https://user-images.githubusercontent.com/23385872/88332857-1f6bf500-cce4-11ea-9c8d-e55ec4136378.png)

**Comment by carmstrong1gw** [comment]
Void, will be fixed with schema UI.
