### ISSUE TITLE
Required Domains/Keys

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#150]
<img width="201" alt="Screen Shot 2020-07-21 at 11 36 35 AM" src="https://user-images.githubusercontent.com/23385872/88093570-0b3ec100-cb47-11ea-99aa-b7682ff340fa.png">

**Comment by jpat1546** [comment]
#146 
#147

**Comment by jpat1546** [comment]
@jpat1546  go through and confirm ALL required fields are included in this issue.

**Comment by carmstrong1gw** [comment]
Void, will be done under schema UI.
