### ISSUE TITLE
A Download button that allows user to download the BCO JSON as a text file.

### ISSUE THREAD

**Issue by openbox-bio** [biocompute-objects/bco_editor#19]

**Comment by HadleyKing** [comment]
Download button works fine
File is valid JSON
please commit, version, and close this issue. :-)

**Comment by openbox-bio** [comment]
OK, thanks Hadley.
-Anjan
=======================================

“Don't be satisfied with stories, how things have gone with others.

Unfold your own myth.”
― Rumi,

========================================

**Comment by openbox-bio** [comment]
Download button has been implemented and is part of version f4720ce
in openbox-bio/bco_editor.

**Comment by CollectorsCorner** [comment]
Hi all, Please enable the download button on the BCO editor on the interface as we are directing non technical users to see BCOs we've created using their experimental data sets. 

Best,
