### ISSUE TITLE
Success pop up message 

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#20]
After #15 was resolved, I noticed the Success pop up box refers to the BCO spec version. It might be more practical to have the BCO ID instead.

So instead of the below, it should say " Success. BCO_000010 has been submitted."
<img width="340" alt="image" src="https://user-images.githubusercontent.com/23385872/62965320-bf31bb00-bdd2-11e9-9b14-e836b934e2a4.png">

**Comment by openbox-bio** [comment]
Noted. Will work on this next week.

**Comment by openbox-bio** [comment]
this is done.
