### ISSUE TITLE
"Do want to leave this page?" Pop-up

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_editor#21]
When a user navigates away from the edit mode with unsaved changes they are prompted with a pop-up that says "Do want to leave this page?" before they loose their wor

**Comment by Anjan-Purkayastha** [comment]
Workflow needs to be expanded. 
What counts as "navigates away"?
We have to give user a choice of actions (a) stay on page (b) continue with navigating away, in addition to a pop-up message.

**Comment by openbox-bio** [comment]
this is done.
