### ISSUE TITLE
Rearrange + add fields in Provenance domain

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#24]
Change to: 
license
name
version 
created
embargo (new- see below)
modified 
contributors

Currently:
![image](https://user-images.githubusercontent.com/23385872/63465391-2a146f00-c42f-11e9-8741-dc0dbfc8a099.png)
![image](https://user-images.githubusercontent.com/23385872/63465681-c2aaef00-c42f-11e9-82e4-5d00ad606710.png)

**Comment by openbox-bio** [comment]
For September 5th, we'll rearrange the domains. 
Suggest to delay embargo fields to mid-September.

**Comment by jpat1546** [comment]
Noted, thanks Anjan. Moving this issue to Milestone 1.5.1 (deadline mid Sept)

**Comment by openbox-bio** [comment]
Fields have been rearranged. We are working on the embargo feature. This should be done by early next week.

**Comment by jpat1546** [comment]
will close in once #26 is complete

**Comment by jpat1546** [comment]
embargo dates fields added - closing this ticket.
#26 is still open to make the embargo dates functional (to establish read only to public access)
