### ISSUE TITLE
Rearrange domains

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#25]
**Currently:**
Top level
Provenance
Description
Execution
Error Domain
Parametric Domain
IO Domain

**Change to:**
Top level - BCO ID, Spec version, Checksum
Provenance Domain
Usability Domain
Description Domain
Execution Domain
Parametric Domain
IO Domain
Error Domain

**Comment by jpat1546** [comment]
location of BCO ID: 
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/23385872/63466381-284bab00-c431-11e9-897a-0f7fa50c89b3.png">

**Comment by openbox-bio** [comment]
Completed on August 30. Please review

**Comment by jpat1546** [comment]
Resolved, thanks!
