### ISSUE TITLE
Create a functional Embargo field 

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#26]
This field should also define permissions- for example, if a user creates a BCO on 8/21, inputs an embargo date from 8/21/19-8/30/19, the BCO will not be made public or viewable on the BCO Editor to other users (with exception to those named as Users/Contributors/ Reviewers)

**Comment by jpat1546** [comment]
aiming for mid/late Sept.

**Comment by openbox-bio** [comment]
Should be done by early next week for testing.

**Comment by openbox-bio** [comment]
Completed. Please test. Note: in this version only BCO author can view before Embargo dates.

**Comment by openbox-bio** [comment]
While entering your BCO details you will see an Object Properties dropdown next to the Edit Json button.
This is feature has been implemented in all the domains. In the Provenance domain select the embargo checkbox dropdown. Selecting this option will cause two fields start date and end date to appear. Add your embargo start and end dates in these fields.

**Comment by jpat1546** [comment]
I can open the Object Properties dropdown (great feature!), but I'm unable to open the provenance domain, so I don't see the embargo checkbox dropdown.

**Comment by openbox-bio** [comment]
it appears if you select the embargo checkbox.
-Anjan
=======================================

“Don't be satisfied with stories, how things have gone with others.

Unfold your own myth.”
― Rumi,

========================================

**Comment by jpat1546** [comment]
Disregard my earlier comment. While there are the embargo start/end fields, they aren't establishing the correct permissions (i.e. hiding them from public view)

**Comment by jpat1546** [comment]
Would it be possible to include the following  "**2019-09-05T08:15:30-05:00 is September 5, 2019, 8:15:30 am, US Eastern Standard Time**"  in the description underneath embargo?

**Comment by openbox-bio** [comment]
Can you send me the BCO ID?
-Anjan
=======================================

“Don't be satisfied with stories, how things have gone with others.

Unfold your own myth.”
― Rumi,

========================================

**Comment by jpat1546** [comment]
https://biocomputeobject.org/bco_editor_tst/BCO_000511

**Comment by openbox-bio** [comment]
I cannot view or access it? What is the embargo date?
-Anjan
=======================================

“Don't be satisfied with stories, how things have gone with others.

Unfold your own myth.”
― Rumi,

========================================

**Comment by openbox-bio** [comment]
FYI, you as the author should be able to access the BCO at any time.
-Anjan
=======================================

“Don't be satisfied with stories, how things have gone with others.

Unfold your own myth.”
― Rumi,

========================================

**Comment by jpat1546** [comment]
embargo:
            "start_time": "2019-09-25T18:12:00-05:00",
            "end_time": "2019-09-26T18:55:00-05:00"
  Hmm...great that you were unable from accessing, but yesterday Amanda was able to access this around 7pm. Since the embargo doesn't expire until this evening, I'll have @HadleyKing 
 and @kee007ney try again this morning.

**Comment by jpat1546** [comment]
I'll consider this ticket done until they get back to us. Thanks Anjan.

**Comment by jpat1546** [comment]
From @HadleyKing  
> I can use the URL to see it but it does not appear in the search for me.

**Comment by jpat1546** [comment]
Could you close this issue with a commit hash? Thanks @openbox-bio
