### ISSUE TITLE
Share option adjacent to "Edit Object"

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#27]
While this is housed in Milestone 1.5, the deadline (realistically) can't be Sept 5. I think we should aim for Sept 23? @openbox-bio let me know how reasonable that deadline is!

This will address 2 issues: 
1. Allowing collaborators to modify/edit an existing object (even to just view it during an embargo period). If we create a “Share” button- they can select permissions for the individual they are sharing with, so long as that individual has an editor account. 
permission options : read only (for collaborators during an embargo period), modify, etc.

**Comment by jpat1546** [comment]
Splitting this ticket into 2- share (#27) and version (#34)

**Comment by jpat1546** [comment]
Share feature is there!
While testing, I received an exception error when attempting to provide more than one individual with read-write permissions. (First individual- permission successfully granted. Second individuals- exception-error-SAVQVQ) 

![image](https://user-images.githubusercontent.com/23385872/65643355-93a01400-dfbf-11e9-91d4-341e39f49e65.png)

**Comment by openbox-bio** [comment]
Thanks. Working on it now.
-Anjan
=======================================

“Don't be satisfied with stories, how things have gone with others.

Unfold your own myth.”
― Rumi,

========================================

**Comment by jpat1546** [comment]
Awesome. In addition- would you be able to view existing permissions? For ex: 
![permissions](https://user-images.githubusercontent.com/23385872/65644290-dd89f980-dfc1-11e9-8be8-3196429dc21f.png)

**Comment by jpat1546** [comment]
Still unable to share read/write permissions with more than one user. 
adding user#1: ![image](https://user-images.githubusercontent.com/23385872/65714393-fef1f080-e068-11e9-948c-997bc1e06365.png)

adding user#2:
![image](https://user-images.githubusercontent.com/23385872/65714487-2a74db00-e069-11e9-855f-dbd48c180ac4.png)

**Comment by jpat1546** [comment]
Ok, so we've been able to select multiple users to share with. Hadley shared BCO_000009 with me (r/w permissions), and I only have read only....
![image](https://user-images.githubusercontent.com/23385872/65720784-ae818f80-e076-11e9-954b-6ed995e4bcd8.png)

and it seems to be parsing the string that is my name into a list of creators...
![image](https://user-images.githubusercontent.com/23385872/65720661-6bbfb780-e076-11e9-9ac1-57074e467dac.png)

**Comment by openbox-bio** [comment]
I shared BCO_000015 with the three of you with varying permissions.
Permissions are being given correctly. Names are being listed correctly as
well.
Hadley will you please share with Janisha again and let me know if the
problem persists?
-Anjan
=======================================

“Don't be satisfied with stories, how things have gone with others.

Unfold your own myth.”
― Rumi,

========================================

**Comment by jpat1546** [comment]
@HadleyKing please share [BCO_000015](https://www.biocomputeobject.org/bco_editor_tst/BCO_000015)  with me again. Thanks!

**Comment by carmstrong1gw** [comment]
Void, moved to API feature.
