### ISSUE TITLE
Indicate field responsible for error message

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#28]
When a user is unable to save due to a Regex issue, in addition to the error message there should be an alert next to the responsible field.  Ex:

![Screen Shot 2019-08-29 at 5 56 48 PM](https://user-images.githubusercontent.com/23385872/63979371-ac7fdd00-ca86-11e9-9878-a37a9c29cd43.png)

**Comment by jpat1546** [comment]
If possible, I think it's important we build this feature in before students use the Editor. So while I think the tentative deadline should be Sept 20, I'll leave that to @kee007ney to decide for his workshop talk

**Comment by openbox-bio** [comment]
Good point. Will talk to my sub and see if we can squeeze this in before September 5th.

**Comment by jpat1546** [comment]
Awesome, thanks Anjan!

**Comment by openbox-bio** [comment]
Implemented on test. Can you please check?

**Comment by jpat1546** [comment]
![image](https://user-images.githubusercontent.com/23385872/64377260-0d179880-cff8-11e9-9d54-bb0de72e2621.png)
Ok, awesome that there's now a field-specific alert. 
The only issue is that since the checksum value is generated automatically and are not input by users, I'm unsure why this is the error message appearing? Maybe I'm misunderstanding, but let's definitely discuss this today on our call.

**Comment by openbox-bio** [comment]
OK, am on call.
-Anjan
=======================================

“Don't be satisfied with stories, how things have gone with others.

Unfold your own myth.”
― Rumi,

========================================

**Comment by openbox-bio** [comment]
Please retest this. I believe we have completed this.

**Comment by jpat1546** [comment]
Ok will do

**Comment by jpat1546** [comment]
Checked- when there's an invalid version format- the error is shown as a new page rather than error message 
![image](https://user-images.githubusercontent.com/23385872/65645067-204cd100-dfc4-11e9-94de-efd358d5e3ae.png)
vs 
![image](https://user-images.githubusercontent.com/23385872/65645082-280c7580-dfc4-11e9-8730-dff71e331b8e.png)
(Left the version field blank, and when attempting to save, the top pic shows the new page. Rather than this, it would be more functional to generate an error message on the Object's page, as was happening before)

**Comment by carmstrong1gw** [comment]
Void, already fixed.
