### ISSUE TITLE
Login error pop up message instead of page

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#31]
Rather than redirect to another page entirely, can there just be an error message generated when a user inputs the incorrect login info?![image](https://user-images.githubusercontent.com/23385872/64376120-83ff6200-cff5-11e9-9562-57b9475bbabe.png)
vs
![image](https://user-images.githubusercontent.com/23385872/64376459-4cdd8080-cff6-11e9-8a66-3b88b53185c3.png)

**Comment by openbox-bio** [comment]
Sounds straightforward. Let's discuss on call.

**Comment by carmstrong1gw** [comment]
Void
