### ISSUE TITLE
"setEditPage, please report this error!"

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#35]
From the home page, if I select "Create Object", this page generates this error. 

![image](https://user-images.githubusercontent.com/23385872/65354345-4c7be280-dbbd-11e9-9ceb-cbee5bc10807.png)

**Comment by openbox-bio** [comment]
Janisha,
I can create an object. Just tried it. Can you please try again?
![Screenshot from 2019-09-22 07:16:21](https://user-images.githubusercontent.com/19177230/65386388-164b7980-dd09-11e9-8997-83f6ef7b0125.png)

**Comment by jpat1546** [comment]
Resolved!

**Comment by jpat1546** [comment]
Closing
