### ISSUE TITLE
Redirect to HTTPS

### ISSUE THREAD

**Issue by nsoranzo** [biocompute-objects/bco_editor#4]
Not sure if it belongs to this repo, but I'd suggest to redirect http://biocomputeobject.org/bco_editor/ to https://biocomputeobject.org/bco_editor/

**Comment by jpat1546** [comment]
It appears that the problem is HTTPS. HTTP works fine without an error. When changing to the HTTPS site, I get the error message. We want the HTTPS site to work and have an auto-redirect from the HTTP. But that can come later

**Comment by HadleyKing** [comment]
Now everything redirects to HTTP. We need it to redirect to HTTPS
