### ISSUE TITLE
Slight Domain Change

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#40]
1. extension_domain to Extension Domain

2. **Under Execution Domain:** 

- external_data_endpoints  to external data endpoints
- environment_variables to environment variables
- software_prerequisites to software prerequisites

3. **Under Input and Output Domain:** 

- input_domain to input domain
- output_subdomain to output subdomain

4. **Under Description Domain:**

- pipeline_steps to pipeline steps

**Comment by jpat1546** [comment]
@openbox-bio I think when the extension_domain was changed to Extension domain, it also changed the sequenced order of domains? 
![image](https://user-images.githubusercontent.com/23385872/65798104-d0464980-e13e-11e9-8ef5-f0950c76c2a1.png)

**Comment by jpat1546** [comment]
![image](https://user-images.githubusercontent.com/23385872/65913266-92932c00-e39d-11e9-8bac-326bb7bb43b4.png)

**Comment by carmstrong1gw** [comment]
Void, now using schema for 4.0.0.
