### ISSUE TITLE
Not breaking checksum?

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#43]
If I change the title of an existing BCO, shouldn't that break the checksum?

**Comment by stain** [comment]
Yes it should, according to the latest P2791/D4 draft (which btw renames `checksum` to [`E-Tag`](https://tools.ietf.org/html/rfc7232#section-2.3) - equivalent as in HTTP.

> Everything except for the `E-Tag`, `object_id`, and `spec_version` shall be included in the generation of an ETag (see https://tools.ietf.org/html/rfc7232#section-2.3) - which can be "strong" or "weak" (see https://tools.ietf.org/html/rfc7232#section-2.1). 

> It is recommended that the ETag be deleted or updated if the object file is changed (except in cases using weak ETags in which the entirety of the change comprises a simple re-writing of the JSON).

**Comment by carmstrong1gw** [comment]
Void, moved to API.
