### ISSUE TITLE
BCO ID link saved by editor

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#47]
the BCO id generated by the editor is: 
"bco_id": "http://biocomputeobject.org/BCO_000531"
This is not a valid link.
Correct would be https://www.biocomputeobject.org/bco_editor_tst/BCO_000531

**Comment by jpat1546** [comment]
![image](https://user-images.githubusercontent.com/23385872/66709268-91171b80-ed2e-11e9-9ef6-0b324c8a4562.png)

**Comment by carmstrong1gw** [comment]
Void, moved to API.
