### ISSUE TITLE
Authors only have read-only permissions to their BCO

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#50]
**Details**: When logged in, user has only read-only permissions to the BCO she created. 
**Troubleshooting efforts**: She showed the issue and tested in front of me. We cleared her cache and did a hard refresh but the issue persisted. 

User:  Nuerye Ainiwan ; BCO: BCO_000539 ; Student issue : [#150](https://github.com/biocompute-objects/GW-SMHS-BIOC6223/issues/150)
User:  Juntian Wei  ;       BCO: BCO_000528 and BCO_000519 ; Student issue :  [#157 ](https://github.com/biocompute-objects/GW-SMHS-BIOC6223/issues/157)
User:  Yuan Gao      ;      BCO: BCO_000544 ; Student issue : [#216 ](https://github.com/biocompute-objects/GW-SMHS-BIOC6223/issues/216)

**Comment by carmstrong1gw** [comment]
Void, moved to API security doc.
