### ISSUE TITLE
Error message: setEditPage, please report this error!

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#51]
**Details:** When a user selected "Create BCO" from home page (https://www.biocomputeobject.org/bco_editor_tst/), she received the following error message: `setEditPage, please report this error!`

**Troubleshooting efforts:** I've asked that she attempt again after clearing her cache and doing a hard refresh. 

User: Zuleima Munoz ; Student issue : [#151 ](https://github.com/biocompute-objects/GW-SMHS-BIOC6223/issues/151)

**Comment by carmstrong1gw** [comment]
Void.
