### ISSUE TITLE
No author listed in home page "created by" column

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#52]
**Details**: Author listed in "created by" column of the BCO from the home page. ( https://www.biocomputeobject.org/bco_editor_tst/)

**Troubleshooting efforts**: Was able to replicate the problem.  Cleared cache and did a hard refresh but the issue persisted. 

User:  Juntian Wei ; BCO: BCO_000519 ; Student issue: [#158  ](https://github.com/biocompute-objects/GW-SMHS-BIOC6223/issues/158)

![image](https://user-images.githubusercontent.com/23385872/67068117-f449e900-f146-11e9-8413-ba0a0d085a6f.png)

**Comment by carmstrong1gw** [comment]
Void, already fixed as of 3.0.1.
