### ISSUE TITLE
"Email" error when saving

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_editor#53]
**Details:** "Email" error message keeps appearing when user tries to save the edited BCO.  It did not highlight a specific field in the BCO, so user was unsure how to troubleshoot. The only email fields in the BCO are Najuma Babirye (BCO creator/author), and David Ting's (an author of the publication). 

**Troubleshooting efforts:** User tried unselecting all email fields, but even then error message is generating when she attempts to save. 

User: Najuma Babirye ; BCO: BCO_000532

![image](https://user-images.githubusercontent.com/23385872/67068160-28250e80-f147-11e9-8afe-785455fa109b.png)
![image](https://user-images.githubusercontent.com/23385872/67068166-307d4980-f147-11e9-9e1a-5535ba422451.png)

**Comment by carmstrong1gw** [comment]
Void, already fixed as of 3.0.1.
