### ISSUE TITLE
Make a deployable 3.0 package

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_editor#58]
- [x] Make a deployable package 
- [x] Upload to Github
- [x] Create a `README.md` and documentation on how to deploy the editor.

**Comment by openbox-bio** [comment]
Hey Hadley,
Can you post the git repo address for version 3.0?
Also you will need to give Manuel rights to commit to repo, if you have not already done so.
itsolution0820@gmail.com

**Comment by HadleyKing** [comment]
@openbox-bio 
I think the best way would be for @ITsolution-git to make a new branch at https://github.com/ITsolution-git/biocompute and make a pull request to [the Dev Branch](https://github.com/biocompute-objects/bco_editor/tree/dev)

**Comment by kee007ney** [comment]
@openbox-bio What's the status on the deployable package? I'd like to get something up on our servers soon so we can begin to get familiar with it in time for the workshop.

**Comment by openbox-bio** [comment]
Manuel has pushed to stage. Can you please check. He is having problems pushing to dev.

**Comment by HadleyKing** [comment]
Done with https://github.com/biocompute-objects/bco_editor/commit/645f4489fca60a03893e44d5a66412d93d491bbd
