### ISSUE TITLE
Semantic URL for editing an individual BCO object. 

### ISSUE THREAD

**Issue by Rahi13** [biocompute-objects/bco_editor#6]
for BCO-editor: use a semantic URL (for e.g: https://data.dev.glygen.org/bco_editor/DSBCO_000001)
while editing the BCO-editor dataset object.

**Comment by jpat1546** [comment]
From the home page (https://www.biocomputeobject.org/bco_editor_tst/), when I click an object (
BCO_000010), the url does not change. It should then reflect (https://www.biocomputeobject.org/bco_editor_tst/BCO_000010)

**Comment by jpat1546** [comment]
@openbox-bio I took another look, and the semantic URL is now in place when selecting individual BCOs! However from [BCO_000004](https://www.biocomputeobject.org/bco_editor_tst/BCO_000004), if a user selects the Tutorial link (on the top header), while it does navigate to the Tutorial page, the URL remains https://www.biocomputeobject.org/bco_editor_tst/BCO_000004.  

Let me know if my ramblings don't make sense. :)

**Comment by openbox-bio** [comment]
OK, let me check.
-Anjan
=======================================

“Don't be satisfied with stories, how things have gone with others.

Unfold your own myth.”
― Rumi,

========================================

**Comment by Anjan-Purkayastha** [comment]
Janisha/Hadley,
We have made the necessary corrections. Can you please review? If semantic URLS are working as expected can you please close issue?
Thank you,
Anjan

**Comment by jpat1546** [comment]
Yes, working as expected!
