### ISSUE TITLE
BioComput Admin - No access

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_editor#64]
At http://ec2-54-146-183-17.compute-1.amazonaws.com:5000/admin
using the following credentials: `anjan.purkayastha@gmail.com; 1234.` gives the following message:
```
You are authenticated as anjan.purkayastha@gmail.com, 
but are not authorized to access this page. 
Would you like to login to a different account?
```

**Comment by openbox-bio** [comment]
Try these credentials:
admin@openboxbio.com
biocompute
-Anjan
=======================================

“Don't be satisfied with stories, how things have gone with others.

Unfold your own myth.”
― Rumi,

========================================
