### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_editor#66]
The profile picture can not be updated or removed.

**Comment by HadleyKing** [comment]
Fixed with 96f32a2d765f2cbe193db6e5aad23dd522cf49ea

**Comment by HadleyKing** [comment]
File upload works but results are not saved.
default needs to be androgynous

**Comment by jpat1546** [comment]
Quickest solution- place a permanent androgynous profile picture there. 
![image](https://user-images.githubusercontent.com/23385872/75797988-f0101800-5d43-11ea-9e65-f90f936ffb69.png)

**Comment by HadleyKing** [comment]
d6a69ee1221c57270784c75f56262e3a59ab667b
