### ISSUE TITLE
Admin Account Documentation

### ISSUE THREAD

**Issue by kee007ney** [biocompute-objects/bco_editor#70]
Do you have some documentation on how to use the admin account that you can send to us, please?

**Comment by openbox-bio** [comment]
Have submitted documentation to Jonathon.
[New_user_sign_up.docx](https://github.com/biocompute-objects/bco_editor/files/4183114/New_user_sign_up.docx)

**Comment by HadleyKing** [comment]
The linked docx should be a MD... Maybe you could do that @jpat1546? include the screen shots?

**Comment by jpat1546** [comment]
https://github.com/biocompute-objects/bco_editor/blob/master/docs/Admin_Account_Documentation.md
[Admin_account_documentation](https://github.com/biocompute-objects/bco_editor/blob/master/docs/Admin_account_documentation.md)

**Comment by jpat1546** [comment]
[Admin_account_documentation](https://github.com/biocompute-objects/bco_editor/blob/master/docs/Admin_account_documentation.md)
