### ISSUE TITLE
No place for 'extension schema' in the BCO editor v 3.0

### ISSUE THREAD

**Issue by Snehby** [biocompute-objects/bco_editor#74]
When working backwards by populating the BCO editor from a test BCO JSON, there is a 'extension_schema' field in two places under the extension_domain field. There doesn't seem to be a place for this link in the BCO editor..
![image](https://user-images.githubusercontent.com/12602831/73779290-83acf380-475a-11ea-8191-e1ec267f5fac.png)

**Comment by HadleyKing** [comment]
Related to #101
