### ISSUE TITLE
xref Access Time format is incorrect under Description Domain in test BCO JSON v 3.0

### ISSUE THREAD

**Issue by Snehby** [biocompute-objects/bco_editor#75]
Under description domain, xref 'access_time's are incorrect - in the format year-day-month, not year-month-day like the rest in the JSON file
![image](https://user-images.githubusercontent.com/12602831/73779714-236a8180-475b-11ea-96e4-37371350e933.png)

**Comment by carmstrong1gw** [comment]
Void, in API.
