### ISSUE TITLE
When sub-sections are minimized under main sections, there is no info about what is in it v 3.0

### ISSUE THREAD

**Issue by Snehby** [biocompute-objects/bco_editor#78]
When sub-sections are minimized under main sections, there should be some information about what is in it. ex: under Provenance Domain, 'Contributor' when minimized under 'contributors'
![image](https://user-images.githubusercontent.com/12602831/73780411-6ed15f80-475c-11ea-9bdc-4857e65a9f7b.png)

These two are filled out with Hadley's information and Eric Donaldson's. Maybe their names should be listed here instead of it being blank.

**Comment by carmstrong1gw** [comment]
Void.
