### ISSUE TITLE
The small grey captions underneath each field should be formatted the same v 3.0

### ISSUE THREAD

**Issue by Snehby** [biocompute-objects/bco_editor#79]
All the small grey captions underneath fields should have the same sentence format (using periods, capitalizing the first letters, etc)
Example under contributor: 
![image](https://user-images.githubusercontent.com/12602831/73780680-e901e400-475c-11ea-8510-12a7378d7cc1.png)
'Name of contributor'
'electronic means of ..'
where the first letter is capitalized for the name but not the email field

Example of embargo fields vs 'derived from' underneath:
![image](https://user-images.githubusercontent.com/12602831/73780828-341bf700-475d-11ea-8843-877aeb34bd7f.png)
Embargo captions capitalize the first letter and have a period at the end of the sentence
Derived from caption doesnt have a period at the end of the second sentence

**Comment by carmstrong1gw** [comment]
Void, re-building frontend UI.
