### ISSUE TITLE
Capitalization of headings/sub-headings should be consistent v 3.0

### ISSUE THREAD

**Issue by Snehby** [biocompute-objects/bco_editor#81]
Capitalization of headings/sub-headings should be consistent

Example comparison between 'contributor' and 'review':
![image](https://user-images.githubusercontent.com/12602831/73781360-1733f380-475e-11ea-9327-c31558b4eaff.png)
'contributor' not capitalized, but sub-section 'Contributors' is capitalized

vs
both 'review' and 'reviewer' are not capitalized
![image](https://user-images.githubusercontent.com/12602831/73781408-316dd180-475e-11ea-88fc-a6dace300717.png)

**Comment by HadleyKing** [comment]
All of the language should follow the specification.
 https://gitlab.com/IEEE-SA/2791/ieee-2791-schema/-/raw/master/2791object.json

**Comment by HadleyKing** [comment]
The duplicate items also need to be distinguished some how.... By numbering or lettering.

**Comment by carmstrong1gw** [comment]
Void, will be fixed with schema UI.
