### ISSUE TITLE
Unable to submit BCO - error domain should be object error

### ISSUE THREAD

**Issue by Snehby** [biocompute-objects/bco_editor#83]
When trying to submit a BCO two errors appear:
.error_domain.empirical_error should be object
.error_domain.algorithmic_error should be object

![image](https://user-images.githubusercontent.com/12602831/74052445-de875a80-49a7-11ea-95e6-81299ae87293.png)
![image](https://user-images.githubusercontent.com/12602831/74052484-f6f77500-49a7-11ea-820b-6c02f5d4950a.png)

**Comment by kee007ney** [comment]
@openbox-bio Make the field free text (@HadleyKing please confirm).
@Snehby for now, please see if you can create a BCO by using this in that field:
{
	"object": "myObject"
}

**Comment by Snehby** [comment]
@kee007ney @HadleyKing 
BCO submits when JSON fields are changed for error domain from 
"error_domain": {
        "empirical_error": "",
        "algorithmic_error": ""
    }
to
"error_domain": {
        "empirical_error": (),
        "algorithmic_error": ()
    }

**Comment by kee007ney** [comment]
@openbox-bio We're testing the Editor right now but it seems to have gotten stuck on the loading screen. Just want to check, are you currently making changes to it?

**Comment by openbox-bio** [comment]
We  are looking into it.
-Anjan
=======================================

“Don't be satisfied with stories, how things have gone with others.

Unfold your own myth.”
― Rumi,

========================================

**Comment by openbox-bio** [comment]
Sneh et al,
Can you please test now?
Note that Error Domain has a default JSON object filled in.
-Anjan
=======================================

“Don't be satisfied with stories, how things have gone with others.

Unfold your own myth.”
― Rumi,

========================================

**Comment by openbox-bio** [comment]
Issue addressed. Please test and close.

**Comment by Snehby** [comment]
Checked, and its fixed
