### ISSUE TITLE
Tutorials Page - spelling error v 3.0

### ISSUE THREAD

**Issue by Snehby** [biocompute-objects/bco_editor#90]
![image](https://user-images.githubusercontent.com/12602831/75059772-a0139480-54ab-11ea-820b-050ed41ee49b.png)

Should be, "**NEW BIOCOMPUTE OBJECT**" instead of "New BCOCOMPUTE Object"

**Comment by HadleyKing** [comment]
https://github.com/biocompute-objects/bco_editor/commit/521359751a91d06fec4add8147c15842a070643d#diff-b3875e5556eda566b1140bcc361f7486
