### ISSUE TITLE
Semantic URL for editing a BCO

### ISSUE THREAD

**Issue by Snehby** [biocompute-objects/bco_editor#91]
For editor, use a semantic URL for BCOs
#6 
current URL:
![image](https://user-images.githubusercontent.com/12602831/75061971-d3f0b900-54af-11ea-997e-8ac9b345d3f9.png)

**Comment by HadleyKing** [comment]
This appears to work but without having issue #109 resolved I can not tell for sure

**Comment by HadleyKing** [comment]
https://github.com/biocompute-objects/bco_editor/pull/106
