### ISSUE TITLE
Check for Duplicate BCO

### ISSUE THREAD

**Issue by Snehby** [biocompute-objects/bco_editor#92]
#12
Check for duplicate BCO:
I made a duplicate BCO but only changed the bco_id and didn't get an error

**Comment by HadleyKing** [comment]
@Snehby  Please test this on the [test](http://ec2-54-146-183-17.compute-1.amazonaws.com/) version and then close if it is complete

**Comment by Snehby** [comment]
I tried 2 things:
- keeping the BCO id that was automatically generated and using the JSON of the rest of the original BCO
- copying and pasting the entire JSON to a new BCO

Both let me make a new object without any error 😢

**Comment by HadleyKing** [comment]
This does not appear to have been addressed yet.

**Comment by carmstrong1gw** [comment]
Fixed in API and also moved to API security document.
